version: '3.5'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /usr/share/pgdata
    ports:
      - 54321:5432
    volumes:
      - ./.docker/pgdata:/usr/share/pgdata
